name: Build and Test

on:
  push

jobs:

  build-and-test-windows:
    name: Build and Test on Windows
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Check Out Source Code
        uses: actions/checkout@v2
      - name: nmake Build
        run: nmake
      - name: Run Executable
        run: .\assignment7.exe

  build-and-test-linux:
    name: Build and Test on Linux
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2
      - name: GNU make Build
        run: make
      - name: Run Executable
        run: ./assignment7
